services:
  client:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    command: npm run start:client:docker
    ports:
      - 4200:4200
    env_file:
      - ./apps/client/.env
    volumes:
      - ./:/app
      - mono-node-modules:/app/node_modules
    networks:
      - default

  socket:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    command: npm run start:socket:docker
    ports:
      - 3000:3000
    volumes:
      - ./:/app
      - mono-node-modules:/app/node_modules
    networks:
      - default

networks:
  default:
    driver: bridge

volumes:
  mono-node-modules: null
